# Generated by Django 4.2.7 on 2024-01-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=150)),
                ('cijena', models.IntegerField()),
                ('max_clanova', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pretplatnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontakt', models.CharField(max_length=20)),
                ('adresa', models.TextField()),
                ('korisnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teretana.korisnik')),
                ('trener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretplatnici', to='teretana.trener')),
            ],
        ),
        migrations.CreateModel(
            name='Pretplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cijena', models.CharField(max_length=50)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teretana.plan')),
                ('pretplatnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teretana.pretplatnik')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tags', models.ManyToManyField(to='teretana.tag')),
            ],
        ),
    ]
