# Generated by Django 4.2.7 on 2024-01-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teretana', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Oznaka',
        ),
        migrations.RenameField(
            model_name='oznaka',
            old_name='name',
            new_name='naziv',
        ),
        migrations.AddField(
            model_name='plan',
            name='oznake',
            field=models.ManyToManyField(related_name='oznake', to='teretana.oznaka'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
