# Generated by Django 4.2.7 on 2024-01-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teretana', '0002_rename_tag_oznaka_rename_name_oznaka_naziv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='oznake',
            field=models.ManyToManyField(blank=True, default=None, related_name='oznake', to='teretana.oznaka'),
        ),
    ]
