# Generated by Django 4.2.7 on 2024-01-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teretana', '0003_alter_plan_oznake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretplatnik',
            name='adresa',
            field=models.CharField(max_length=150),
        ),
    ]
