# Generated by Django 4.2.7 on 2024-01-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teretana', '0004_alter_pretplatnik_adresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretplata',
            name='cijena',
            field=models.IntegerField(),
        ),
    ]
